const sampleListings = [
    {
      "bookid": "1",
      "title": "Introduction to Problem Solving",
      "subtitle": "A Step-by-Step Guide",
      "author": "John Doe",
      "price": 45.99,
      "image": "intro_problem_solving.jpg",
      "edition": 1,
      "language": "English",
      "quantity": 10,
      "branch": "Computer Science and Engineering",
      "description": "This book introduces fundamental problem-solving techniques.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "2",
      "title": "Programming Fundamentals",
      "subtitle": "Concepts and Practices",
      "author": "Jane Smith",
      "price": 55.50,
      "image": "programming_fundamentals.jpg",
      "edition": 2,
      "language": "English",
      "quantity": 5,
      "branch": "Computer Science and Engineering",
      "description": "An essential guide to programming fundamentals and practices.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "3",
      "title": "Python Programming",
      "subtitle": "For Beginners",
      "author": "Alice Johnson",
      "price": 39.99,
      "image": "python_programming.jpg",
      "edition": 3,
      "language": "English",
      "quantity": 15,
      "branch": "Computer Science and Engineering",
      "description": "A beginner's guide to programming in Python.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "4",
      "title": "C Programming",
      "subtitle": "Basics to Advanced",
      "author": "Michael Brown",
      "price": 48.75,
      "image": "c_programming.jpg",
      "edition": 4,
      "language": "English",
      "quantity": 7,
      "branch": "Computer Science and Engineering",
      "description": "Comprehensive guide on C programming from basics to advanced.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "5",
      "title": "Java Programming",
      "subtitle": "Step by Step",
      "author": "Emily Davis",
      "price": 52.30,
      "image": "java_programming.jpg",
      "edition": 5,
      "language": "English",
      "quantity": 8,
      "branch": "Computer Science and Engineering",
      "description": "Step-by-step guide to learning Java programming.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "6",
      "title": "Algorithms and Data Structures",
      "subtitle": "Essentials for Problem Solving",
      "author": "Chris Wilson",
      "price": 60.00,
      "image": "algorithms_data_structures.jpg",
      "edition": 1,
      "language": "English",
      "quantity": 20,
      "branch": "Computer Science and Engineering",
      "description": "An essential guide to algorithms and data structures for problem solving.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "7",
      "title": "C++ Programming",
      "subtitle": "From Basics to Advanced",
      "author": "Nancy Lee",
      "price": 49.99,
      "image": "cpp_programming.jpg",
      "edition": 2,
      "language": "English",
      "quantity": 10,
      "branch": "Computer Science and Engineering",
      "description": "A complete guide to C++ programming, from basics to advanced.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "8",
      "title": "Problem Solving with JavaScript",
      "subtitle": "For Beginners and Experts",
      "author": "David Clark",
      "price": 44.95,
      "image": "problem_solving_javascript.jpg",
      "edition": 3,
      "language": "English",
      "quantity": 12,
      "branch": "Computer Science and Engineering",
      "description": "A comprehensive guide to problem solving with JavaScript.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "9",
      "title": "Introduction to Algorithms",
      "subtitle": "A Problem-Solving Approach",
      "author": "Sandra Martinez",
      "price": 57.20,
      "image": "introduction_algorithms.jpg",
      "edition": 4,
      "language": "English",
      "quantity": 9,
      "branch": "Computer Science and Engineering",
      "description": "An introduction to algorithms with a focus on problem solving.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "10",
      "title": "R Programming",
      "subtitle": "A Beginner's Guide",
      "author": "Paul Anderson",
      "price": 46.80,
      "image": "r_programming.jpg",
      "edition": 5,
      "language": "English",
      "quantity": 6,
      "branch": "Computer Science and Engineering",
      "description": "A beginner's guide to programming in R for problem solving.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "11",
      "title": "Ruby Programming",
      "subtitle": "Easy Steps for Beginners",
      "author": "Jennifer Moore",
      "price": 50.50,
      "image": "ruby_programming.jpg",
      "edition": 1,
      "language": "English",
      "quantity": 18,
      "branch": "Computer Science and Engineering",
      "description": "Easy steps to learn Ruby programming for beginners.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "12",
      "title": "Perl Programming",
      "subtitle": "From Novice to Professional",
      "author": "Robert Taylor",
      "price": 42.30,
      "image": "perl_programming.jpg",
      "edition": 2,
      "language": "English",
      "quantity": 7,
      "branch": "Computer Science and Engineering",
      "description": "A comprehensive guide to Perl programming from novice to professional.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "13",
      "title": "Swift Programming",
      "subtitle": "For Apple Developers",
      "author": "Patricia Thomas",
      "price": 53.45,
      "image": "swift_programming.jpg",
      "edition": 3,
      "language": "English",
      "quantity": 5,
      "branch": "Computer Science and Engineering",
      "description": "Guide to Swift programming for Apple developers.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "14",
      "title": "MATLAB Programming",
      "subtitle": "An Introductory Guide",
      "author": "Daniel Jackson",
      "price": 56.20,
      "image": "matlab_programming.jpg",
      "edition": 4,
      "language": "English",
      "quantity": 14,
      "branch": "Computer Science and Engineering",
      "description": "An introductory guide to MATLAB programming for problem solving.",
      "subject": "Programming for Problem Solving",
    },
    {
      "bookid": "15",
      "title": "Functional Programming",
      "subtitle": "Concepts and Practices",
      "author": "Steven White",
      "price": 51.99,
      "image": "functional_programming.jpg",
      "edition": 5,
      "language": "English",
      "quantity": 11,
      "branch": "Computer Science and Engineering",
      "description": "An essential guide to functional programming concepts and practices.",
      "subject": "Programming for Problem Solving",
    },
  {
    "bookid": "001",
    "title": "Mastering C++",
    "subtitle": "Comprehensive Guide to OOP",
    "author": "John Doe",
    "price": 45.99,
    "image": "image1.jpg",
    "edition": 3,
    "language": "English",
    "quantity": 50,
    "branch": "Computer Science and Engineering",
    "description": "An in-depth exploration of object-oriented programming concepts using C++.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "002",
    "title": "Effective C++",
    "subtitle": "55 Specific Ways to Improve Your Programs and Designs",
    "author": "Scott Meyers",
    "price": 39.99,
    "image": "image2.jpg",
    "edition": 1,
    "language": "English",
    "quantity": 30,
    "branch": "Computer Science and Engineering",
    "description": "Essential advice for improving your C++ coding skills.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "003",
    "title": "C++ Primer",
    "subtitle": "Best Practices for OOP",
    "author": "Stanley Lippman",
    "price": 59.99,
    "image": "image3.jpg",
    "edition": 5,
    "language": "English",
    "quantity": 40,
    "branch": "Computer Science and Engineering",
    "description": "A comprehensive guide to the basics and advanced topics of C++.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "004",
    "title": "The C++ Programming Language",
    "subtitle": "Definitive Guide to OOP",
    "author": "Bjarne Stroustrup",
    "price": 64.99,
    "image": "image4.jpg",
    "edition": 4,
    "language": "English",
    "quantity": 20,
    "branch": "Computer Science and Engineering",
    "description": "Authored by the creator of C++, this book is a must-have for any C++ programmer.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "005",
    "title": "Object-Oriented Programming in C++",
    "subtitle": "Advanced Concepts",
    "author": "Robert Lafore",
    "price": 49.99,
    "image": "image5.jpg",
    "edition": 4,
    "language": "English",
    "quantity": 35,
    "branch": "Computer Science and Engineering",
    "description": "A detailed guide on OOP concepts and how to implement them in C++.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "006",
    "title": "Programming: Principles and Practice Using C++",
    "subtitle": "From Beginner to Professional",
    "author": "Bjarne Stroustrup",
    "price": 54.99,
    "image": "image6.jpg",
    "edition": 2,
    "language": "English",
    "quantity": 45,
    "branch": "Computer Science and Engineering",
    "description": "A comprehensive guide to programming principles using C++, authored by its creator.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "007",
    "title": "C++ Programming: From Problem Analysis to Program Design",
    "subtitle": "Structured Approach to OOP",
    "author": "D.S. Malik",
    "price": 42.99,
    "image": "image7.jpg",
    "edition": 7,
    "language": "English",
    "quantity": 25,
    "branch": "Computer Science and Engineering",
    "description": "A structured approach to learning C++ programming and OOP.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "008",
    "title": "C++ for Programmers",
    "subtitle": "OOP Techniques and Practices",
    "author": "Paul Deitel",
    "price": 69.99,
    "image": "image8.jpg",
    "edition": 3,
    "language": "English",
    "quantity": 60,
    "branch": "Computer Science and Engineering",
    "description": "An advanced guide to programming in C++ with a focus on OOP techniques.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "009",
    "title": "Accelerated C++",
    "subtitle": "Practical Programming by Example",
    "author": "Andrew Koenig",
    "price": 34.99,
    "image": "image9.jpg",
    "edition": 1,
    "language": "English",
    "quantity": 15,
    "branch": "Computer Science and Engineering",
    "description": "A practical approach to learning C++ with real-world examples.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "010",
    "title": "C++ Design Patterns",
    "subtitle": "Reusable Object-Oriented Software",
    "author": "Erich Gamma",
    "price": 59.99,
    "image": "image10.jpg",
    "edition": 1,
    "language": "English",
    "quantity": 10,
    "branch": "Computer Science and Engineering",
    "description": "A detailed guide on design patterns and their implementation in C++.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "001",
    "title": "Mastering C++",
    "subtitle": "Comprehensive Guide to OOP",
    "author": "John Doe",
    "price": 45.99,
    "image": "image1.jpg",
    "edition": 3,
    "language": "English",
    "quantity": 50,
    "branch": "Computer Science and Engineering",
    "description": "An in-depth exploration of object-oriented programming concepts using C++.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "002",
    "title": "Effective C++",
    "subtitle": "55 Specific Ways to Improve Your Programs and Designs",
    "author": "Scott Meyers",
    "price": 39.99,
    "image": "image2.jpg",
    "edition": 1,
    "language": "English",
    "quantity": 30,
    "branch": "Computer Science and Engineering",
    "description": "Essential advice for improving your C++ coding skills.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "003",
    "title": "C++ Primer",
    "subtitle": "Best Practices for OOP",
    "author": "Stanley Lippman",
    "price": 59.99,
    "image": "image3.jpg",
    "edition": 5,
    "language": "English",
    "quantity": 40,
    "branch": "Computer Science and Engineering",
    "description": "A comprehensive guide to the basics and advanced topics of C++.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "004",
    "title": "The C++ Programming Language",
    "subtitle": "Definitive Guide to OOP",
    "author": "Bjarne Stroustrup",
    "price": 64.99,
    "image": "image4.jpg",
    "edition": 4,
    "language": "English",
    "quantity": 20,
    "branch": "Computer Science and Engineering",
    "description": "Authored by the creator of C++, this book is a must-have for any C++ programmer.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "005",
    "title": "Object-Oriented Programming in C++",
    "subtitle": "Advanced Concepts",
    "author": "Robert Lafore",
    "price": 49.99,
    "image": "image5.jpg",
    "edition": 4,
    "language": "English",
    "quantity": 35,
    "branch": "Computer Science and Engineering",
    "description": "A detailed guide on OOP concepts and how to implement them in C++.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "006",
    "title": "Programming: Principles and Practice Using C++",
    "subtitle": "From Beginner to Professional",
    "author": "Bjarne Stroustrup",
    "price": 54.99,
    "image": "image6.jpg",
    "edition": 2,
    "language": "English",
    "quantity": 45,
    "branch": "Computer Science and Engineering",
    "description": "A comprehensive guide to programming principles using C++, authored by its creator.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "007",
    "title": "C++ Programming: From Problem Analysis to Program Design",
    "subtitle": "Structured Approach to OOP",
    "author": "D.S. Malik",
    "price": 42.99,
    "image": "image7.jpg",
    "edition": 7,
    "language": "English",
    "quantity": 25,
    "branch": "Computer Science and Engineering",
    "description": "A structured approach to learning C++ programming and OOP.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "008",
    "title": "C++ for Programmers",
    "subtitle": "OOP Techniques and Practices",
    "author": "Paul Deitel",
    "price": 69.99,
    "image": "image8.jpg",
    "edition": 3,
    "language": "English",
    "quantity": 60,
    "branch": "Computer Science and Engineering",
    "description": "An advanced guide to programming in C++ with a focus on OOP techniques.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "009",
    "title": "Accelerated C++",
    "subtitle": "Practical Programming by Example",
    "author": "Andrew Koenig",
    "price": 34.99,
    "image": "image9.jpg",
    "edition": 1,
    "language": "English",
    "quantity": 15,
    "branch": "Computer Science and Engineering",
    "description": "A practical approach to learning C++ with real-world examples.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "010",
    "title": "C++ Design Patterns",
    "subtitle": "Reusable Object-Oriented Software",
    "author": "Erich Gamma",
    "price": 59.99,
    "image": "image10.jpg",
    "edition": 1,
    "language": "English",
    "quantity": 10,
    "branch": "Computer Science and Engineering",
    "description": "A detailed guide on design patterns and their implementation in C++.",
    "subject": "Object Oriented Programming Using C++",
  },
  {
    "bookid": "1",
    "title": "Introduction to Algorithms",
    "subtitle": "A Comprehensive Guide",
    "author": "Thomas H. Cormen",
    "price": 89.99,
    "image": "intro_to_algorithms.jpg",
    "edition": 4,
    "language": "English",
    "quantity": 50,
    "branch": "Computer Science and Engineering",
    "description": "An in-depth guide to algorithms, covering a range of topics from basic to advanced levels.",
    "subject": "Data Structure and Algorithm",
  },
  {
    "bookid": "2",
    "title": "Algorithms Unlocked",
    "subtitle": "Understand Algorithms in a Simple Way",
    "author": "Thomas H. Cormen",
    "price": 39.99,
    "image": "algorithms_unlocked.jpg",
    "edition": 1,
    "language": "English",
    "quantity": 30,
    "branch": "Computer Science and Engineering",
    "description": "A book that demystifies algorithms and explains their principles in an easy-to-understand manner.",
    "subject": "Data Structure and Algorithm",
  },
  {
    "bookid": "3",
    "title": "Data Structures and Algorithms in Java",
    "subtitle": "An In-depth Guide",
    "author": "Robert Lafore",
    "price": 59.99,
    "image": "ds_algorithms_java.jpg",
    "edition": 3,
    "language": "English",
    "quantity": 40,
    "branch": "Computer Science and Engineering",
    "description": "Learn about data structures and algorithms with a focus on Java implementation.",
    "subject": "Data Structure and Algorithm",
  },
  {
    "bookid": "4",
    "title": "Data Structures and Algorithm Analysis in C++",
    "subtitle": "Detailed Analysis and Examples",
    "author": "Mark Allen Weiss",
    "price": 79.99,
    "image": "ds_algo_cpp.jpg",
    "edition": 4,
    "language": "English",
    "quantity": 25,
    "branch": "Computer Science and Engineering",
    "description": "Comprehensive coverage of data structures and algorithms with C++ implementations.",
    "subject": "Data Structure and Algorithm",
  },
  {
    "bookid": "5",
    "title": "Grokking Algorithms",
    "subtitle": "An illustrated guide for programmers and other curious people",
    "author": "Aditya Bhargava",
    "price": 45.00,
    "image": "grokking_algorithms.jpg",
    "edition": 1,
    "language": "English",
    "quantity": 60,
    "branch": "Computer Science and Engineering",
    "description": "A fun and easy guide to understanding algorithms, complete with illustrations and examples.",
    "subject": "Data Structure and Algorithm",
  },
  {
    bookid: "001",
    title: "Computer Organization and Design",
    subtitle: "The Hardware/Software Interface",
    author: "David A. Patterson, John L. Hennessy",
    price: 89.99,
    image: "link_to_image1",
    edition: 5,
    language: "English",
    quantity: 15,
    branch: "Computer Science and Engineering",
    description: "An essential guide to computer organization and architecture, offering a comprehensive view of hardware/software interface.",
    subject: "Computer Organisation and Architecture",
},
{
    bookid: "002",
    title: "Structured Computer Organization",
    subtitle: "",
    author: "Andrew S. Tanenbaum, Todd Austin",
    price: 74.99,
    image: "link_to_image2",
    edition: 6,
    language: "English",
    quantity: 10,
    branch: "Computer Science and Engineering",
    description: "A classic text that covers the concepts and models of computer architecture in detail.",
    subject: "Computer Organisation and Architecture",
},
{
    bookid: "003",
    title: "Computer Architecture: A Quantitative Approach",
    subtitle: "",
    author: "John L. Hennessy, David A. Patterson",
    price: 92.50,
    image: "link_to_image3",
    edition: 6,
    language: "English",
    quantity: 8,
    branch: "Computer Science and Engineering",
    description: "A comprehensive guide to understanding computer architecture through quantitative analysis.",
    subject: "Computer Organisation and Architecture",
},
{
    bookid: "004",
    title: "Digital Design and Computer Architecture",
    subtitle: "",
    author: "David Harris, Sarah Harris",
    price: 85.00,
    image: "link_to_image4",
    edition: 2,
    language: "English",
    quantity: 12,
    branch: "Computer Science and Engineering",
    description: "This book integrates digital design principles with computer architecture concepts.",
    subject: "Computer Organisation and Architecture",
},
{
    bookid: "005",
    title: "Modern Computer Architecture and Organization",
    subtitle: "",
    author: "Jim Ledin",
    price: 79.99,
    image: "link_to_image5",
    edition: 1,
    language: "English",
    quantity: 20,
    branch: "Computer Science and Engineering",
    description: "An up-to-date guide on modern computer architecture and organization.",
    subject: "Computer Organisation and Architecture",
},
{
    bookid: "OS001",
    title: "Operating System Concepts",
    subtitle: "The Essentials",
    author: "Abraham Silberschatz",
    price: 79.99,
    image: "os_concepts.jpg",
    edition: 10,
    language: "English",
    quantity: 15,
    branch: "Computer Science and Engineering",
    description: "An introduction to operating system concepts, focusing on the core aspects.",
    subject: "Operating System",
},
{
    bookid: "OS002",
    title: "Modern Operating Systems",
    subtitle: "Fourth Edition",
    author: "Andrew S. Tanenbaum",
    price: 89.99,
    image: "modern_os.jpg",
    edition: 4,
    language: "English",
    quantity: 20,
    branch: "Computer Science and Engineering",
    description: "Comprehensive coverage of operating systems, including design and implementation.",
    subject: "Operating System",
},
{
    bookid: "OS003",
    title: "Operating Systems: Three Easy Pieces",
    subtitle: "A Hands-On Approach",
    author: "Remzi H. Arpaci-Dusseau",
    price: 65.00,
    image: "three_easy_pieces.jpg",
    edition: 1,
    language: "English",
    quantity: 30,
    branch: "Computer Science and Engineering",
    description: "Explains core operating system concepts using practical examples.",
    subject: "Operating System",
},
{
    bookid: "OS004",
    title: "Linux Kernel Development",
    subtitle: "Third Edition",
    author: "Robert Love",
    price: 55.00,
    image: "linux_kernel_dev.jpg",
    edition: 3,
    language: "English",
    quantity: 10,
    branch: "Computer Science and Engineering",
    description: "In-depth guide to Linux kernel programming and development.",
    subject: "Operating System",
},
{
    bookid: "OS005",
    title: "Operating Systems: Internals and Design Principles",
    subtitle: "Eighth Edition",
    author: "William Stallings",
    price: 99.99,
    image: "os_internals.jpg",
    edition: 8,
    language: "English",
    quantity: 25,
    branch: "Computer Science and Engineering",
    description: "Detailed coverage of the internal mechanisms and design principles of modern operating systems.",
    subject: "Operating System",
},
{
    bookid: "CSE-DAA-001",
    title: "Introduction to Algorithms",
    subtitle: "A Comprehensive Guide",
    author: "Thomas H. Cormen",
    price: 50.00,
    image: "intro_to_algorithms.jpg",
    edition: 3,
    language: "English",
    quantity: 5,
    branch: "Computer Science and Engineering",
    description: "This book offers a comprehensive introduction to the modern study of computer algorithms.",
    subject: "Design and Analysis of Algorithm",
},
{
    bookid: "CSE-DAA-002",
    title: "Algorithms Unlocked",
    subtitle: "Simplified Algorithm Concepts",
    author: "Thomas H. Cormen",
    price: 40.00,
    image: "algorithms_unlocked.jpg",
    edition: 1,
    language: "English",
    quantity: 10,
    branch: "Computer Science and Engineering",
    description: "An accessible introduction to the study of algorithms for anyone interested in understanding how computers solve problems.",
    subject: "Design and Analysis of Algorithm",
},
{
    bookid: "CSE-DAA-003",
    title: "Algorithm Design",
    subtitle: "Fundamentals and Strategies",
    author: "Jon Kleinberg",
    price: 60.00,
    image: "algorithm_design.jpg",
    edition: 1,
    language: "English",
    quantity: 3,
    branch: "Computer Science and Engineering",
    description: "Focuses on fundamental principles of algorithm design and analysis.",
    subject: "Design and Analysis of Algorithm",
},
{
    bookid: "CSE-DAA-004",
    title: "The Algorithm Design Manual",
    subtitle: "Strategies and Insights",
    author: "Steven S. Skiena",
    price: 55.00,
    image: "algorithm_design_manual.jpg",
    edition: 2,
    language: "English",
    quantity: 7,
    branch: "Computer Science and Engineering",
    description: "Provides straightforward access to combinatorial algorithms technology.",
    subject: "Design and Analysis of Algorithm",
},
{
    bookid: "CSE-DAA-005",
    title: "Data Structures and Algorithm Analysis",
    subtitle: "In C",
    author: "Mark Allen Weiss",
    price: 45.00,
    image: "ds_algo_analysis_c.jpg",
    edition: 2,
    language: "English",
    quantity: 8,
    branch: "Computer Science and Engineering",
    description: "An updated, and comprehensive introduction to data structures and algorithm analysis.",
    subject: "Design and Analysis of Algorithm",
},
{
    bookid: "CE1001",
    title: "Digital Electronics Fundamentals",
    subtitle: "A Comprehensive Guide",
    author: "John Smith",
    price: 45.99,
    image: "digital_electronics_fundamentals.jpg",
    edition: 2,
    language: "English",
    quantity: 50,
    branch: "Computer Science and Engineering",
    description: "This book covers the basics and advanced topics in digital electronics.",
    subject: "Digital Electronics",
},
{
    bookid: "CE1002",
    title: "Principles of Digital Design",
    subtitle: "Hands-On Approach",
    author: "Alice Johnson",
    price: 55.50,
    image: "principles_of_digital_design.jpg",
    edition: 3,
    language: "English",
    quantity: 30,
    branch: "Computer Science and Engineering",
    description: "An essential guide for understanding digital design principles.",
    subject: "Digital Electronics",
},
{
    bookid: "CE1003",
    title: "Digital Logic and Computer Design",
    subtitle: "Foundations and Applications",
    author: "David Brown",
    price: 65.25,
    image: "digital_logic_and_computer_design.jpg",
    edition: 5,
    language: "English",
    quantity: 25,
    branch: "Computer Science and Engineering",
    description: "Covers the theory and practical aspects of digital logic and design.",
    subject: "Digital Electronics",
},
{
    bookid: "CE1004",
    title: "Introduction to Verilog HDL",
    subtitle: "Programming for Digital Electronics",
    author: "Michael Clark",
    price: 49.99,
    image: "introduction_to_verilog_hdl.jpg",
    edition: 4,
    language: "English",
    quantity: 40,
    branch: "Computer Science and Engineering",
    description: "Learn Verilog HDL programming for digital electronics applications.",
    subject: "Digital Electronics",
},
{
    bookid: "CE1005",
    title: "Digital Electronics and Microprocessors",
    subtitle: "Integration and Applications",
    author: "Sarah White",
    price: 59.75,
    image: "digital_electronics_and_microprocessors.jpg",
    edition: 3,
    language: "English",
    quantity: 35,
    branch: "Computer Science and Engineering",
    description: "Explores the intersection of digital electronics and microprocessors.",
    subject: "Digital Electronics",
},
{
    bookid: "CS101",
    title: "Database Management Systems",
    subtitle: "Concepts and Applications",
    author: "Abraham Silberschatz, Henry F. Korth, S. Sudarshan",
    price: 45.99,
    image: "dbms.jpg",
    edition: 6,
    language: "English",
    quantity: 20,
    branch: "Computer Science and Engineering",
    description: "Comprehensive guide to database management systems.",
    subject: "Database Management System",
},
{
    bookid: "CS102",
    title: "Fundamentals of Database Systems",
    subtitle: "RDBMS, NoSQL, and Big Data",
    author: "Ramez Elmasri, Shamkant B. Navathe",
    price: 55.50,
    image: "fundamentals-db.jpg",
    edition: 7,
    language: "English",
    quantity: 15,
    branch: "Computer Science and Engineering",
    description: "Covers relational, NoSQL, and big data databases.",
    subject: "Database Management System",
},
{
    bookid: "CS103",
    title: "SQL Performance Explained",
    subtitle: "Everything Developers Need to Know about SQL Performance",
    author: "Markus Winand",
    price: 39.95,
    image: "sql-performance.jpg",
    edition: 3,
    language: "English",
    quantity: 10,
    branch: "Computer Science and Engineering",
    description: "Focuses on optimizing SQL queries and database performance.",
    subject: "Database Management System",
},
{
    bookid: "CS104",
    title: "NoSQL Distilled",
    subtitle: "A Brief Guide to the Emerging World of Polyglot Persistence",
    author: "Martin Fowler, Pramod J. Sadalage",
    price: 29.99,
    image: "nosql-distilled.jpg",
    edition: 1,
    language: "English",
    quantity: 12,
    branch: "Computer Science and Engineering",
    description: "Introduces NoSQL databases and their applications.",
    subject: "Database Management System",
},
{
    bookid: "CS105",
    title: "Database Systems: The Complete Book",
    subtitle: "Global Edition",
    author: "Hector Garcia-Molina, Jeffrey D. Ullman, Jennifer Widom",
    price: 65.00,
    image: "complete-db-book.jpg",
    edition: 2,
    language: "English",
    quantity: 18,
    branch: "Computer Science and Engineering",
    description: "Comprehensive coverage of database system concepts.",
    subject: "Database Management System",
},
{
    bookid: "AI101",
    title: "Artificial Intelligence: A Modern Approach",
    subtitle: "3rd Edition",
    author: "Stuart Russell, Peter Norvig",
    price: 45.99,
    image: "ai_book1.jpg",
    edition: 3,
    language: "English",
    quantity: 25,
    branch: "Computer Science and Engineering",
    description: "Comprehensive introduction to AI covering key concepts and applications.",
    subject: "Artificial Intelligence",
},
{
    bookid: "AI102",
    title: "Machine Learning",
    subtitle: "Algorithms and Applications",
    author: "Mohammed Zaki, Wagner Meira Jr.",
    price: 55.50,
    image: "ai_book2.jpg",
    edition: 2,
    language: "English",
    quantity: 15,
    branch: "Computer Science and Engineering",
    description: "Explains fundamental ML algorithms with practical examples.",
    subject: "Artificial Intelligence",
},
{
    bookid: "AI103",
    title: "Deep Learning",
    subtitle: "From Basics to Practice",
    author: "Andrew Glassner",
    price: 39.95,
    image: "ai_book3.jpg",
    edition: 1,
    language: "English",
    quantity: 30,
    branch: "Computer Science and Engineering",
    description: "Covers deep learning concepts and applications in various domains.",
    subject: "Artificial Intelligence",
},
{
    bookid: "AI104",
    title: "Natural Language Processing with Python",
    subtitle: "Analyzing Text with the Natural Language Toolkit",
    author: "Steven Bird, Ewan Klein, Edward Loper",
    price: 49.99,
    image: "ai_book4.jpg",
    edition: 3,
    language: "English",
    quantity: 20,
    branch: "Computer Science and Engineering",
    description: "Practical guide to NLP techniques using Python and NLTK library.",
    subject: "Artificial Intelligence",
},
{
    bookid: "AI105",
    title: "Reinforcement Learning",
    subtitle: "An Introduction",
    author: "Richard S. Sutton, Andrew G. Barto",
    price: 42.00,
    image: "ai_book5.jpg",
    edition: 2,
    language: "English",
    quantity: 18,
    branch: "Computer Science and Engineering",
    description: "Introduction to reinforcement learning algorithms and applications.",
    subject: "Artificial Intelligence",
},
{
    bookid: "CS101",
    title: "Software Engineering: A Practitioner's Approach",
    subtitle: "Global Edition",
    author: "Roger S. Pressman",
    price: 45.99,
    image: "software_engineering.jpg",
    edition: 8,
    language: "English",
    quantity: 100,
    branch: "Computer Science and Engineering",
    description: "Comprehensive guide to software engineering practices and methodologies.",
    subject: "Software Engineering",
},
{
    bookid: "CS102",
    title: "Introduction to Software Engineering",
    subtitle: "",
    author: "Ian Sommerville",
    price: 38.50,
    image: "intro_to_se.jpg",
    edition: 10,
    language: "English",
    quantity: 80,
    branch: "Computer Science and Engineering",
    description: "Fundamental principles of software engineering for beginners.",
    subject: "Software Engineering",
},
{
    bookid: "CS103",
    title: "Software Engineering: Theory and Practice",
    subtitle: "",
    author: "Shari Lawrence Pfleeger",
    price: 55.00,
    image: "se_theory_practice.jpg",
    edition: 4,
    language: "English",
    quantity: 65,
    branch: "Computer Science and Engineering",
    description: "In-depth exploration of software engineering theories and practical applications.",
    subject: "Software Engineering",
},
{
    bookid: "CS104",
    title: "Software Engineering for Embedded Systems",
    subtitle: "Methods, Practical Techniques, and Applications",
    author: "Robert Oshana",
    price: 62.99,
    image: "se_embedded.jpg",
    edition: 2,
    language: "English",
    quantity: 50,
    branch: "Computer Science and Engineering",
    description: "Focuses on software engineering practices specific to embedded systems.",
    subject: "Software Engineering",
},
{
    bookid: "CS105",
    title: "Agile Software Development: Principles, Patterns, and Practices",
    subtitle: "",
    author: "Robert C. Martin",
    price: 48.75,
    image: "agile_se.jpg",
    edition: 3,
    language: "English",
    quantity: 75,
    branch: "Computer Science and Engineering",
    description: "Guide to agile methodologies in software development.",
    subject: "Software Engineering",
},
{
    bookid: "CS101",
    title: "Principles of Compiler Design",
    subtitle: "Theory and Practice",
    author: "Alfred V. Aho, Jeffrey D. Ullman",
    price: 45.99,
    image: "compiler_design.jpg",
    edition: 2,
    language: "English",
    quantity: 15,
    branch: "Computer Science and Engineering",
    description: "Comprehensive guide covering principles and practical aspects of compiler design.",
    subject: "Compiler Design",
},
{
    bookid: "CS102",
    title: "Modern Compiler Implementation in C",
    subtitle: "Basic Techniques",
    author: "Andrew W. Appel",
    price: 39.95,
    image: "modern_compiler_c.jpg",
    edition: 3,
    language: "English",
    quantity: 10,
    branch: "Computer Science and Engineering",
    description: "Covers the essentials of compiler design with a focus on practical implementation.",
    subject: "Compiler Design",
},
{
    bookid: "CN001",
    title: "Computer Networks: A Top-Down Approach",
    subtitle: "6th Edition",
    author: "James F. Kurose, Keith W. Ross",
    price: 45.99,
    image: "networks.jpg",
    edition: 6,
    language: "English",
    quantity: 100,
    branch: "Computer Science and Engineering",
    description: "Comprehensive introduction to computer networks with a focus on the Internet and applications.",
    subject: "Computer Networks",
},
{
    bookid: "CN002",
    title: "Data Communications and Networking",
    subtitle: "5th Edition",
    author: "Behrouz A. Forouzan",
    price: 55.00,
    image: "data_comm.jpg",
    edition: 5,
    language: "English",
    quantity: 80,
    branch: "Computer Science and Engineering",
    description: "Fundamental concepts of data communications and networking technologies.",
    subject: "Computer Networks",
},
{
    bookid: "ML101",
    title: "Hands-On Machine Learning with Scikit-Learn",
    subtitle: "Concepts, Tools, and Techniques for Building Intelligent Systems",
    author: "Aurélien Géron",
    price: 45.99,
    image: "ml101-cover.jpg",
    edition: 2,
    language: "English",
    quantity: 20,
    branch: "Computer Science and Engineering",
    description: "Comprehensive guide to machine learning with practical examples using Scikit-Learn and TensorFlow.",
    subject: "Machine Learning",
},
{
    bookid: "ML102",
    title: "Pattern Recognition and Machine Learning",
    subtitle: "Information Science and Statistics",
    author: "Christopher M. Bishop",
    price: 55.00,
    image: "ml102-cover.jpg",
    edition: 1,
    language: "English",
    quantity: 15,
    branch: "Computer Science and Engineering",
    description: "Classic text on pattern recognition and machine learning algorithms.",
    subject: "Machine Learning",
},

//electrical eng

{
  bookid: "1",
  title: "Fundamentals of Analog Electronics",
  subtitle: "A Comprehensive Guide",
  author: "John Doe",
  price: 59.99,
  image: "image1.jpg",
  edition: 3,
  language: "English",
  quantity: 10,
  branch: "electrical",
  description: "An essential book covering the fundamentals of analog electronics.",
  subject: "analog electronics"
},
{
  bookid: "2",
  title: "Analog Circuits and Systems",
  subtitle: "Design and Applications",
  author: "Jane Smith",
  price: 45.50,
  image: "image2.jpg",
  edition: 2,
  language: "English",
  quantity: 15,
  branch: "electrical",
  description: "This book explores the design and applications of analog circuits.",
  subject: "analog electronics"
},
];

module.exports = { data: sampleListings };

























          
